export type Priority = 'High' | 'Medium' | 'Low';

// Category types for tasks
export type Category = 'Study' | 'College' | 'Teaching' | 'Personal' | 'Health' | 'Skill Development';

export interface Task {
  id: string;
  title: string;
  description?: string;
  category: Category;
  priority: Priority;
  startTime: string; // e.g., "07:00 AM"
  endTime?: string;
  completed: boolean;
  userId: string;
  date: string; // ISO string date (YYYY-MM-DD)
  isAutoGenerated: boolean;
}

export interface UserProfile {
  uid: string;
  displayName: string;
  email: string;
  photoURL?: string;
  streak: number;
  lastCompletedDate?: string;
  routineConfig?: RoutineConfig;
}

export interface RoutineConfig {
  wakeUp: string;
  collegeStart: string;
  collegeEnd: string;
  lunchStart: string;
  lunchEnd: string;
  teachingStart: string;
  teachingEnd: string;
  studyStart: string;
  studyEnd: string;
}
