import type { Task } from '../types';

export const WEEKDAY_ROUTINE: Omit<Task, 'id' | 'userId' | 'date' | 'completed' | 'isAutoGenerated'>[] = [
  { title: "Wake up", startTime: "07:00 AM", category: "Personal", priority: "Medium" },
  { title: "College Session", startTime: "08:15 AM", endTime: "03:30 PM", category: "College", priority: "High" },
  { title: "Lunch Break", startTime: "11:00 AM", endTime: "11:30 AM", category: "Health", priority: "Medium" },
  { title: "Home Return/Travel", startTime: "03:30 PM", endTime: "04:00 PM", category: "Personal", priority: "Low" },
  { title: "Tuition Teaching", startTime: "04:30 PM", endTime: "08:00 PM", category: "Teaching", priority: "High" },
  { title: "Evening Routine", startTime: "08:00 PM", endTime: "09:00 PM", category: "Personal", priority: "Medium" },
  { title: "Study (Java, DSA, React)", startTime: "09:00 PM", endTime: "12:00 AM", category: "Study", priority: "High" },
  { title: "Sleep", startTime: "12:00 AM", category: "Health", priority: "High" },
];

export const WEEKEND_ROUTINE: Omit<Task, 'id' | 'userId' | 'date' | 'completed' | 'isAutoGenerated'>[] = [
  { title: "Wake up (Late)", startTime: "08:30 AM", category: "Health", priority: "Medium" },
  { title: "Morning Exercise", startTime: "09:30 AM", category: "Health", priority: "Medium" },
  { title: "Skill Development (Project)", startTime: "10:30 AM", endTime: "01:00 PM", category: "Skill Development", priority: "High" },
  { title: "Lunch & Relaxation", startTime: "01:00 PM", endTime: "02:30 PM", category: "Personal", priority: "Low" },
  { title: "Revision (DSA Concepts)", startTime: "03:00 PM", endTime: "05:00 PM", category: "Study", priority: "High" },
  { title: "Teaching Prep", startTime: "05:30 PM", endTime: "07:30 PM", category: "Teaching", priority: "Medium" },
  { title: "Personal Time / Fun", startTime: "08:00 PM", endTime: "10:00 PM", category: "Personal", priority: "Low" },
  { title: "Weekly Planning", startTime: "10:30 PM", endTime: "11:30 PM", category: "Skill Development", priority: "Medium" },
  { title: "Sleep", startTime: "12:00 AM", category: "Health", priority: "High" },
];

export const SUGGESTIONS = [
  "Revise Java Stream API",
  "Solve 2 LeetCode Medium problems",
  "Implement a custom hook in React",
  "Drink 3 liters of water today",
  "Stretch for 10 minutes",
  "Read 5 pages of a technical book"
];

export const MOTIVATIONAL_QUOTES = [
  "The only way to do great work is to love what you do.",
  "Your struggle today is your strength tomorrow.",
  "Don't stop when you're tired. Stop when you're done.",
  "Code like you're changing the world.",
  "Progress, not perfection."
];
