import React, { createContext, useContext, useEffect, useState } from 'react';
import { useAuth } from './AuthContext';
import type { Task } from '../types';
import { WEEKDAY_ROUTINE, WEEKEND_ROUTINE } from '../utils/routineData';
import { format, isWeekend } from 'date-fns';

interface TaskContextType {
  tasks: Task[];
  addTask: (task: Omit<Task, 'id' | 'userId'>) => Promise<void>;
  updateTask: (id: string, updates: Partial<Task>) => Promise<void>;
  deleteTask: (id: string) => Promise<void>;
  generateDailyRoutine: () => Promise<void>;
  productivityProgress: number;
}

const TaskContext = createContext<TaskContextType | undefined>(undefined);

export const TaskProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();
  const [tasks, setTasks] = useState<Task[]>([]);
  const today = format(new Date(), 'yyyy-MM-dd');

  // Load from local storage
  useEffect(() => {
    if (!user) {
      setTasks([]);
      return;
    }

    const savedTasks = localStorage.getItem(`tasks_${user.uid}`);
    if (savedTasks) {
      const parsedTasks = JSON.parse(savedTasks) as Task[];
      // Filter for today and sort by start time
      const todaysTasks = parsedTasks
        .filter(t => t.date === today)
        .sort((a, b) => a.startTime.localeCompare(b.startTime));
      setTasks(todaysTasks);
    }
  }, [user, today]);

  // Helper to save to local storage
  const saveTasks = (newTasks: Task[]) => {
    if (!user) return;
    setTasks(newTasks);
    
    // We get all tasks, replace today's tasks, and save back
    const allSaved = localStorage.getItem(`tasks_${user.uid}`);
    let allTasks: Task[] = allSaved ? JSON.parse(allSaved) : [];
    
    // Remove old tasks for today
    allTasks = allTasks.filter(t => t.date !== today);
    // Add new tasks for today
    allTasks = [...allTasks, ...newTasks];
    
    localStorage.setItem(`tasks_${user.uid}`, JSON.stringify(allTasks));
  };

  const addTask = async (task: Omit<Task, 'id' | 'userId'>) => {
    if (!user) return;
    const newTask: Task = {
      ...task,
      id: Math.random().toString(36).substr(2, 9),
      userId: user.uid,
    };
    
    const newTasks = [...tasks, newTask].sort((a, b) => a.startTime.localeCompare(b.startTime));
    saveTasks(newTasks);
  };

  const updateTask = async (id: string, updates: Partial<Task>) => {
    const newTasks = tasks.map(t => t.id === id ? { ...t, ...updates } : t);
    saveTasks(newTasks);
  };

  const deleteTask = async (id: string) => {
    const newTasks = tasks.filter(t => t.id !== id);
    saveTasks(newTasks);
  };

  const generateDailyRoutine = async () => {
    if (!user) return;

    if (tasks.length === 0) {
      const isWeekEnd = isWeekend(new Date());
      const routine = isWeekEnd ? WEEKEND_ROUTINE : WEEKDAY_ROUTINE;

      const generatedTasks: Task[] = routine.map(item => ({
        ...item,
        id: Math.random().toString(36).substr(2, 9),
        userId: user.uid,
        date: today,
        completed: false,
        isAutoGenerated: true,
      }));

      saveTasks(generatedTasks);
    }
  };

  const productivityProgress = tasks.length > 0 
    ? (tasks.filter(t => t.completed).length / tasks.length) * 100 
    : 0;

  return (
    <TaskContext.Provider value={{ 
      tasks, 
      addTask, 
      updateTask, 
      deleteTask, 
      generateDailyRoutine,
      productivityProgress
    }}>
      {children}
    </TaskContext.Provider>
  );
};

export const useTasks = () => {
  const context = useContext(TaskContext);
  if (context === undefined) {
    throw new Error('useTasks must be used within a TaskProvider');
  }
  return context;
};

